- import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: ms_vnc_enabled|bool
  tags:
    - setup-all
    - setup-ms-vnc

- import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: not ms_vnc_enabled|bool
  tags:
    - setup-all
    - setup-ms-vnc

