
- name: vino disable remote access.
  dconf:
    key: '/org/gnome/desktop/remote-access/enabled'
    value: 'false'
  become: yes
  become_user: "{{ ms_vino_user }}"

- name: vino disable prompt
  dconf:
    key: '/org/gnome/desktop/remote-access/prompt-enabled'
    value: 'true'   
  become: yes
  become_user: "{{ ms_vino_user }}"

- name: vino /org/gnome/desktop/remote-access/require-encryption
  dconf:
    key: '/org/gnome/desktop/remote-access/require-encryption'
    value: 'true'   
  become: yes
  become_user: "{{ ms_vino_user }}"
